### PR TITLE
Dark theme based on System Theme

### LINKED ISSUE #13: Dark theme based on System Theme
A Checkbox of checked the theme will change based on the system theme, else the toggle switch changes the theme.

### PR DESCRIPTION
**Pull request by rosekamallove**
## Please, go through these steps before you submit a PR.

- [x] You've explained what the Pull Request is adding.
- [x] You've explained why this is important.

Added them toggle based on system theme, user can choose between whether the theme will change based on the system theme or based on the toggle switch.

Fixes #13 

systemDarkDemo2-2021-07-21_19 14 17

### CODE REVIEW

**Comment by hkaur008** [comment]
Hey ! @rosekamallove Can you move the **js folder** to the **assets folder** . As it would give a clearer outlook to project files workflow.

**Comment by rosekamallove** [comment]
Okay on it

**Comment by rosekamallove** [comment]
**Done**

**Comment by awilkescom** [comment]
Works great. 

@rosekamallove just a tip, don't add the checkboxes in your PR messages, just the updates themselves will do :)

**Pull request merged**
