### PR TITLE
Improvements in Projects and Project Details Page

### PR DESCRIPTION
**Pull request by rishavnaskar**
## Improvements made so far

- [x] Added ***Page Link Preview*** when mouse cursor hovers over any project.
- [x] Added *Lottie Animations* at the bottom of Project Details page.
- [x] Added custom *.scss* files for additional dark theme.
Working on Issue #4 

### Screenshots for Reference

**Page Link Preview**             |  **Lottie Animations in Dark Theme**
:-------------------------:|:-------------------------:
  |

### CODE REVIEW

**Comment by rosekamallove** [comment]
Hey, @rishavnaskar it looks like you created completely new CSS files for light and dark themes, instead, you should use the variables defined in `_scss/theme.scss` to make the whole project consistent. Maybe add more variables if required.

- The theme switcher doesn't seem to work too.
- And instead of putting your JS in your HTML, putting it in a separate file is better.

**Comment by rishavnaskar** [comment]
> Hey, @rishavnaskar it looks like you created completely new CSS files for light and dark themes, instead, you should use the variables defined in `_scss/theme.scss` to make the whole project consistent. Maybe add more variables if required.
> 
> - The theme switcher doesn't seem to work too.
> - And instead of putting your JS in your HTML, putting it in a separate file is better.

Hey. Thank you for mentioning about '_scss/theme.scss'. I will look into this for sure. 
Although my aim was not to implement a dark theme toggle as its already been taken up by someone else. I have just added my own version of dark theme. By default, this dark theme of mine wont be applied. One has to manually change the import in 'assets/css/main.scss'. 

If it creates problems, I will surely remove it.

**Comment by rosekamallove** [comment]
> > Hey, @rishavnaskar it looks like you created completely new CSS files for light and dark themes, instead, you should use the variables defined in `_scss/theme.scss` to make the whole project consistent. Maybe add more variables if required.
> > 
> > * The theme switcher doesn't seem to work too.
> > * And instead of putting your JS in your HTML, putting it in a separate file is better.
> 
> Hey. Thank you for mentioning about '_scss/theme.scss'. I will look into this for sure.
> Although my aim was not to implement a dark theme toggle as its already been taken up by someone else. I have just added my own version of dark theme. By default, this dark theme of mine wont be applied. One has to manually change the import in 'assets/scss/main.scss'.
> 
> If it creates problems, I will surely remove it.

Yes, all you have to do is create a diff file for your script, and use the variables defined in `_sass/themes.scss` instead of creating multiple `sass` files create one and use variables instead of hardcoded values. And the theme toggler will change the theme for your PR as well.

**Comment by awilkescom** [comment]
Hi @rishavnaskar 

I really like the mouse-over page preview, nice one. However I couldn't see the project details page additions you made in relation to your screenshot - in fact it seems like a whole new page structure.

Could you please update the PR with the updated information about the new page template?

Also I noticed one of the images was much wider than the content area. I think it would look better if you made the image fit the column?

image

**Comment by rishavnaskar** [comment]
> Hi @rishavnaskar
> 
> I really like the mouse-over page preview, nice one. However I couldn't see the project details page additions you made in relation to your screenshot - in fact it seems like a whole new page structure.
> 
> Could you please update the PR with the updated information about the new page template?
> 
> Also I noticed one of the images was much wider than the content area. I think it would look better if you made the image fit the column?
> 
> image

Yeah I just noticed. It was actually done by my teammate @ananya0504 . We will fix this asap.

**Comment by rishavnaskar** [comment]
## I have made the necessary changes to the file

#### The page now looks like this. Hopefully this solves the issues

image

**Comment by awilkescom** [comment]
Ok cool, looks much smarter! Nice one!

**Pull request merged**
