### PR TITLE
Updated all pages with new UI in Flutter

### PR DESCRIPTION
**Pull request by rishavnaskar**
## New UI in Flutter

- [x] Recreated the home page in Flutter
- [x] Customized background with new image
- [x] Added custom animations
Referenced to Issue #20

### CODE REVIEW

**Comment by awilkescom** [comment]
Hi @rishavnaskar 

I get this when i try to build the project

Is there updated guidance for building the project, now it's using flutter?

image

**Comment by rishavnaskar** [comment]
> Hi @rishavnaskar
> 
> I get this when i try to build the project
> 
> Is there updated guidance for building the project, now it's using flutter?
> 
> image

Yes I was about to update the readme soon.

## Steps to run
- [ ] Download Flutter sdk.
- [ ] Add flutter sdk to environment path.
- [ ] switch to flutter master channel by running "flutter channel master" in cmd.
- [ ] Clone the repository
- [ ] Run "flutter pub get"
- [ ] Run "flutter run -d chrome" (considering you have chrome browser installed. If not, replace chrome with browser name)
- [ ] You can get the list of supported devices by running "flutter doctor" or "flutter devices"

**Comment by awilkescom** [comment]
@rishavnaskar Ah ok! I think it would be helpful to explain people step-by-step for the installation so it's clear for others (people in our pod might be brand new to flutter). Could you please expand the "steps to run" (e.g. link to the Flutter SDK, provide any guidance that's needed for Windows/Mac/Linux, how to add to path, how to switch to flutter master etc). Then I would also include an updated readme.md in your PR.

**Comment by rishavnaskar** [comment]
> @rishavnaskar Ah ok! I think it would be helpful to explain people step-by-step for the installation so it's clear for others (people in our pod might be brand new to flutter). Could you please expand the "steps to run" (e.g. link to the Flutter SDK, provide any guidance that's needed for Windows/Mac/Linux, how to add to path, how to switch to flutter master etc). Then I would also include an updated readme.md in your PR.

Yep, did this. Sorry for being late.

**Comment by awilkescom** [comment]
Cool - looks much better. Thanks both!

**Pull request merged**
